=== GeorgeWang1994/was-installer/deployment/wastopology.xsd
<?xml version="1.0" encoding="UTF-8"?>
   <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.gr.ibm.com"
xmlns="http://www.gr.ibm.com" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="wastopology">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="server" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="application" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="webserver" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="name" use="required"/>
                            <xs:attribute type="xs:string" name="nodename" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="sharedlib" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="name" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name" use="required"/>
                  <xs:attribute type="xs:string" name="earfileptrn" use="required"/>
                  <xs:attribute type="xs:string" name="vhost" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="xs:string" name="nodename" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="cluster">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="application" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="webserver">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="name" use="required"/>
                            <xs:attribute type="xs:string" name="nodename" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name" use="required"/>
                  <xs:attribute type="xs:string" name="earfileptrn" use="required"/>
                  <xs:attribute type="xs:string" name="vhost" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== GeorgeWang1994/was-installer/deployment/topology.sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<wastopology xmlns="http://www.gr.ibm.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gr.ibm.com wastopology.xsd">
	<server name="mysrv" nodename="mynodeNode01">
		<application name="app1" earfileptrn="app1-ear." vhost="default_host"></application>
		<application name="app2" earfileptrn="app2-sample-ear." vhost="default_host">
			<webserver name="ihs1" nodename="ihs1-node"/>
			<webserver name="ihs2" nodename="ihs2-node"/>
		</application>
		<application name="app3" earfileptrn="app3-sample-ear." vhost="default_host">
			<sharedlib name="My Shared lib"/>
			<webserver name="ihs1" nodename="ihs1-node"/>
		</application>
	</server>
	<cluster name="mycluster">
		<application name="app4" earfileptrn="app4-ear-" vhost="default_host">
			<webserver name="ihs1" nodename="ihs1-node"/>
		</application>
	</cluster>
</wastopology>
